### ISSUE TITLE
Random test failures due to invalid prefix replacement

### ISSUE THREAD

**Issue by beenje** [prefix-dev/rattler-build#264] opened 2023-11-07 16:00 UTC
We are testing replacing `conda mambabuild` with `rattler-build` in our internal gitlab ci pipelines.

We are testing for simple noarch python packages. The recipe is generated with grayskull and converted with boa and looks like:

```
context:
  name: sardana-restarter
  version: 2.4.1.dev1+g38ea727
package:
  name: '{{ name|lower }}'
  version: '{{ version }}'
source:
  url: file:///builds/kits-maxiv/app-maxiv-sardanarestarter/dist/sardana-restarter-2.4.1.dev1+g38ea727.tar.gz
  sha256: 679533ee101897c05bd5d1d7345afab3d25280badf4373eef8b19107ca1a8bd6
build:
  entry_points:
    - sardana-restart = sardanarestarter.sardanarestarter:main
  noarch: python
  script: 'python -m pip install . -vv'
  number: 0
requirements:
  host:
    - python
    - setuptools >=45
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python
    - pytango
    - pyqt
test:
  imports:
    - sardanarestarter
  commands:
    - pip check
    - sardana-restart --help
  requires:
    - pip
about:
  home: https://gitlab.maxiv.lu.se/kits-maxiv/app-maxiv-sardanarestarter
  summary: Sardana restarter to restart Pool and MacroServer or any device server using tango
  license: LGPL-3.0
  license_file: LICENSE
```

We had already 2 or 3 occurrences where the test phase failed. For example:

```
✔ Successfully updated the environment
Collecting tests from "/var/lib/containers/.cache/rattler/cache/pkgs/sardana-restarter-2.4.1.dev1+g38ea727-pyh4616a5c_0"
Testing commands:
+ pip check
No broken requirements found.
+ sardana-restart --help
/var/lib/containers/.cache/rattler/cache/pkgs/sardana-restarter-2.4.1.dev1+g38ea727-pyh4616a5c_0/info/test/run_test.sh: /tmp/rattler-build_sardana-restarter_1699362325375/work/test/bin/sardana-restart: /tmp/rattler-buil/tmp/rattler-build_sardana-restarter_1699362325375/work/test/: bad interpreter: No such file or directory
2023-11-07T13:05:54.635951Z ERROR rattler_build: Error: failed to run test
```

If we run the pipeline again, it passes:

```
✔ Successfully updated the environment
Collecting tests from "/var/lib/containers/.cache/rattler/cache/pkgs/sardana-restarter-2.4.1.dev1+g38ea727-pyh4616a5c_0"
Testing commands:
+ pip check
No broken requirements found.
+ sardana-restart --help
usage: sardana-restart [-h] [--all] [--pool] [--macroserver] [--widget]
                       [--device-server DEVICESERVER]
Sardana restarter to restart Pool and MacroServer or any device server using
tango
options:
  -h, --help            show this help message and exit
...
Testing Python imports:
import sardanarestarter
✔ all tests passed!
```

The path `/tmp/rattler-buil/tmp/rattler-build_sardana-restarter_1699362325375/work/test/` looks suspicious.
Any idea where this could come from?

We are using version 0.4.0.

**Comment by beenje** [comment] 2023-11-08 10:23
I ran a bunch of pipelines this night and got a few extra occurrences:

```
Collecting tests from "/var/lib/containers/.cache/rattler/cache/pkgs/tangods-balderpandabox-1.0.0-pyh4616a5c_0"
Testing commands:
+ pip check
No broken requirements found.
+ BalderPandabox --help
/var/lib/containers/.cache/rattler/cache/pkgs/tangods-balderpandabox-1.0.0-pyh4616a5c_0/info/test/run_test.sh: /tmp/rattler-build_tangods-balderpandabox_1699376992085/work/test/bin/BalderPandabox: /tmp/rattler-buil/tmp/rattler-build_tangods-balderpandabox_1699376992085/work/: bad interpreter: No such file or directory
```

```
Collecting tests from "/var/lib/containers/.cache/rattler/cache/pkgs/tangods-nanos-bmc101-10.0.4.dev1+gcb2164d-pyh4616a5c_0"
Testing commands:
+ pip check
No broken requirements found.
+ NanosBmc101 --help
/var/lib/containers/.cache/rattler/cache/pkgs/tangods-nanos-bmc101-10.0.4.dev1+gcb2164d-pyh4616a5c_0/info/test/run_test.sh: /tmp/rattler-build_tangods-nanos-bmc101_1699374455177/work/test/bin/NanosBmc101: /tmp/rattler-buil/tmp/rattler-build_tangods-nanos-bmc101_1699374455177/work/te: bad interpreter: No such file or directory
2023-11-07T16:27:53.380206Z ERROR rattler_build: Error: failed to run test
```

Again:
- `/tmp/rattler-buil/tmp/rattler-build_tangods-balderpandabox_1699376992085/work/`: bad interpreter: No such file or directory
- `/tmp/rattler-buil/tmp/rattler-build_tangods-nanos-bmc101_1699374455177/work/te`: bad interpreter: No such file or directory

In all cases, there is a `/tmp/rattler-buil` extra string at the start.

**Comment by beenje** [comment] 2023-11-08 10:45
I could reproduce locally after several runs:

```
Testing commands:
+ pip check
No broken requirements found.
+ MASsoft --help
/root/.cache/rattler/cache/pkgs/tangods-massoft-1.3.0-pyh4616a5c_0/info/test/run_test.sh: /tmp/rattler-build_tangods-massoft_1699440115359/work/test/bin/MASsoft: /tmp/rattler-buil/tmp/rattler-build_tangods-massoft_1699440115359/work/test/bi: bad interpreter: No such file or directory
2023-11-08T10:42:02.732317Z ERROR rattler_build: Error: failed to run test

cat /tmp/rattler-build_tangods-massoft_1699440115359/work/test/bin/MASsoft
#!/tmp/rattler-buil/tmp/rattler-build_tangods-massoft_1699440115359/work/test/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from massoftds.server import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

Looking in the package:

```
cat python-scripts/MASsoft
#!/bin/sh
'''exec' /tmp/rattler-build_tangods-massoft_1699440115359/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from massoftds.server import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

There seems to be an issue with the prefix replacement.

**Comment by wolfv** [comment] 2023-11-14 10:59
@beenje do you have by chance the "broken" package?

**Comment by beenje** [comment] 2023-11-14 20:04
No, but I reproduced it again. You can download the package [here](https://lunduniversityo365-my.sharepoint.com/:u:/g/personal/be3488be_lu_se/EbkF-ZxTAalGo10N9LbIK4QBkkUt1CPMcJrn7OKYI81oDg?e=MzIaTg)

Do you want any file from the build directory (`/tmp/rattler-build_sardana-restarter_1699977805519`)?

**Comment by wolfv** [comment] 2023-11-16 12:01
Hi @beenje I am looking at this right now. 
I see that there is a `python-script` that contains the prefix.

The paths.json specifies:

```json
    {
      "_path": "python-scripts/sardana-restart",
      "path_type": "hardlink",
      "file_mode": "text",
      "prefix_placeholder": "/tmp/rattler-build_sardana-restarter_1699977805519/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place",
      "sha256": "c65aea08a24179c41bd5e8ab12260a47c0226372bfe1be5d407acbfa5859456d",
      "size_in_bytes": 515
    },
```

And the top of the script looks like:

#!/bin/sh
'''exec' /tmp/rattler-build_sardana-restarter_1699977805519/host_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python "$0" "$@"
' '''

I'll check further why prefix replacement would fail here.

**Comment by wolfv** [comment] 2023-11-16 12:02
Hmm, ok, one other issue is that you also specify the script as an entry point. I believe, technically, the `python-script` should therefore not exist at all (only the entry point in `link.json`).

I actually think this might be fixed in the next release ...

**Comment by wolfv** [comment] 2023-11-16 12:03
Is that package / recipe open source? I could try to reproduce this locally in that case. Otherwise need to write my own recipe :)

**Comment by wolfv** [comment] 2023-11-16 16:52
There was an issue where we created both an entrypoint as well as a `python-script` for `noarch` packages. I think that is where this was coming from ... and then some weird interaction with our parallel / async way of linking files.

Anyways, it should be fixed by https://github.com/prefix-dev/rattler-build/pull/301

Thanks again for reporting!

**Comment by beenje** [comment] 2023-11-17 12:48
Great! Looking forward for next release :-)

**Comment by wolfv** [comment] 2023-11-17 12:55
Going to close this for now, releasing today, and then let me know if it's still an issue! This helped catch a couple bugs, btw. so thanks!

**Closed by wolfv** 2023-11-17 12:55 UTC
